/**
 * Property tests: P6 (Hook File Round-Trip) + P7 (Hook Command Format).
 *
 * Feature: kiro-ide-hook-shim, Property 6: Hook File Round-Trip
 * Feature: kiro-ide-hook-shim, Property 7: Hook Command Format
 *
 * P6: For any hook file object generated by the installer,
 * JSON.parse(JSON.stringify(hookFile, null, 2)) produces a deeply equal object.
 *
 * P7: For any shim path (including paths with spaces), then.command contains
 * the quoted path, the event type argument, and ends with ` || true`.
 *
 * Validates: Requirements 13.2, 1.8, 13.4
 */

import { describe, expect, it } from 'vitest';
import fc from 'fast-check';

import { ideHookFileArb, shimPathArb } from '../helpers/arbitrary.js';

// ── Property tests ──────────────────────────────────────────────────────

describe('IDE hook files — P6 + P7 property tests', () => {
  it('P6: hook file round-trips through JSON serialization', () => {
    fc.assert(
      fc.property(
        ideHookFileArb(),
        (hookFile) => {
          const serialized = JSON.stringify(hookFile, null, 2);
          const deserialized = JSON.parse(serialized) as unknown;

          // P6: round-trip must produce a deeply equal object
          expect(deserialized).toEqual(hookFile);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('P7: then.command contains quoted shim path, event type, and || true', () => {
    fc.assert(
      fc.property(
        ideHookFileArb(),
        (hookFile) => {
          const command = hookFile.then.command;
          const eventType = hookFile.when.type;

          // P7: command must end with ` || true`
          expect(command).toMatch(/ \|\| true$/);

          // P7: command must contain the event type as an argument
          expect(command).toContain(eventType);

          // P7: command must start with a quoted path
          expect(command).toMatch(/^"[^"]+"/);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('P7: shim paths with spaces are properly quoted in commands', () => {
    fc.assert(
      fc.property(
        shimPathArb(),
        fc.constantFrom('promptSubmit', 'agentStop', 'postToolUse'),
        (shimPath, eventType) => {
          const command = `"${shimPath}" ${eventType} || true`;

          // P7: command must end with ` || true`
          expect(command).toMatch(/ \|\| true$/);

          // P7: the shim path must be quoted
          expect(command.startsWith(`"${shimPath}"`)).toBe(true);

          // P7: command must contain the event type
          expect(command).toContain(eventType);
        },
      ),
      { numRuns: 100 },
    );
  });
});
