/**
 * Property tests: P6 (Hook File Round-Trip) + P7 (Hook Command/Prompt Format).
 *
 * Feature: kiro-ide-hook-shim, Property 6: Hook File Round-Trip
 * Feature: ide-stop-hook-askagent, Property 1: Stop Hook Uses askAgent
 * Feature: ide-stop-hook-askagent, Property 2: Prompt and Tool Hooks Use runCommand
 *
 * P6: For any hook file object generated by the installer,
 * JSON.parse(JSON.stringify(hookFile, null, 2)) produces a deeply equal object.
 *
 * P7: For runCommand hooks, then.command contains the quoted path, the event
 * type argument, and ends with ` || true`. For askAgent hooks, then.prompt is
 * a non-empty string and then.command is absent.
 *
 * Validates: Requirements 1.1, 1.2, 1.3, 2.1, 2.2, 4.4
 */

import { describe, expect, it } from 'vitest';
import fc from 'fast-check';

import { ideHookFileArb } from '../helpers/arbitrary.js';

// ── Property tests ──────────────────────────────────────────────────────

describe('IDE hook files — P6 + P7 property tests', () => {
  /**
   * **Property 4: Hook File Round-Trip**
   * **Validates: Requirements 4.4**
   */
  it('P6: hook file round-trips through JSON serialization', () => {
    fc.assert(
      fc.property(
        ideHookFileArb(),
        (hookFile) => {
          const serialized = JSON.stringify(hookFile, null, 2);
          const deserialized = JSON.parse(serialized) as unknown;

          // P6: round-trip must produce a deeply equal object
          expect(deserialized).toEqual(hookFile);
        },
      ),
      { numRuns: 100 },
    );
  });

  /**
   * **Property 1: Stop Hook Uses askAgent, Property 2: Prompt and Tool Hooks Use runCommand**
   * **Validates: Requirements 1.1, 1.2, 1.3, 2.1, 2.2**
   */
  it('P7: runCommand hooks have correct command format, askAgent hooks have non-empty prompt', () => {
    fc.assert(
      fc.property(
        ideHookFileArb(),
        (hookFile) => {
          if (hookFile.then.type === 'runCommand') {
            const command = hookFile.then.command;
            const eventType = hookFile.when.type;

            // runCommand: command must end with ` || true`
            expect(command).toMatch(/ \|\| true$/);

            // runCommand: command must contain the event type as an argument
            expect(command).toContain(eventType);

            // runCommand: command must start with a quoted path
            expect(command).toMatch(/^"[^"]+"/);

            // runCommand hooks should not be agentStop events
            expect(eventType).not.toBe('agentStop');
          } else {
            // askAgent: prompt must be a non-empty string
            expect(hookFile.then.type).toBe('askAgent');
            expect(hookFile.then.prompt).toBeDefined();
            expect(typeof hookFile.then.prompt).toBe('string');
            expect(hookFile.then.prompt.trim().length).toBeGreaterThan(0);

            // askAgent: command must be absent
            expect((hookFile.then as Record<string, unknown>)['command']).toBeUndefined();

            // askAgent hooks should be agentStop events
            expect(hookFile.when.type).toBe('agentStop');
          }
        },
      ),
      { numRuns: 100 },
    );
  });
});
